### ISSUE TITLE
English translation for menus?

### ISSUE THREAD

**Issue by TheAnonUser** [jankinT/DerpiViewer#1]
Hi
Sorry to bother, I found this app but it is not translated to English, I mean about the menus.

Maybe in the next alpha?

Also I found that the user have to tap search instead of the search of the keyboard

**Comment by jankinT** [comment]
Sorry for the delay, the English version will be made at some point, and the search input will be fix on the lattest version.
My English sucks, so if you find my grammar wierd, I'm sorry for that.

**Comment by TheAnonUser** [comment]
Don't worry, this take some time and we are not robots
Thank you for the response

**Comment by jankinT** [comment]
I'm very happy to inform you, the English version has been included in. I hope you Enjoy this App, if you find any issue, feel free to let me know, I'll try my best to fix it.
Thanks for your support!

**Comment by jankinT** [comment]
this is the latest version
https://github.com/jankinT/DerpiViewer/releases/tag/Alphla1.1.0

**Comment by TheAnonUser** [comment]
Thank you !
I will close this issue
